import type { QuestionnaireInput } from "@/lib/validation/questionnaire";

export const DEMO_CASES: Record<
  string,
  { label: string; description: string; data: QuestionnaireInput }
> = {
  "customer-service-chatbot": {
    label: "Kundenservice-Chatbot",
    description:
      "Generative KI auf der Website — Kunden interagieren direkt, kein KI-Hinweis, keine Vorabprüfung.",
    data: {
      name: "Kundenservice-Chatbot „Helena“",
      description:
        "Generativer Chatbot auf der Unternehmenswebsite zur Beantwortung von Kundenanfragen.",
      department: "Kundenservice",
      status: "PRODUCTION",
      purpose: "Kundenanfragen schnell und rund um die Uhr beantworten.",
      process: "First-Level-Kundensupport auf der Website",
      aiType: "GENERATIVE",
      provider: "OpenAI",
      model: "GPT-4o",
      usageType: "EXTERNAL",
      affectedPersons: ["CUSTOMERS"],
      decisionType: "INFORMATION_ONLY",
      dataCategories: ["PERSONAL_DATA"],
      dataTransferredToExternal: "YES",
      humanReview: "NO",
      approvalProcess: "NO",
      outputControl: "NO",
      logging: "YES",
      interventionAvailable: "NO",
      escalationProcess: "YES",
      directHumanInteraction: "YES",
      aiUsageNotice: "NO",
      aiGeneratedContentPublished: "YES",
      contentHumanReviewed: "NO",
      responsibleRole: "Leiter Kundenservice",
      trainingProvided: "YES",
      usageRulesDefined: "YES",
      recruitmentScenario: false,
      candidatePrioritisation: false,
      candidateSelection: false,
      qualityChecks: "UNKNOWN",
      biasChecks: "UNKNOWN",
      providerApproval: "YES",
      isDemo: true,
      demoKey: "customer-service-chatbot",
    },
  },
  "cv-screening": {
    label: "CV-Vorsortierung",
    description:
      "KI priorisiert Bewerbungen — Bewerberdaten, finale Entscheidung durch Mensch, keine Bias-Prüfung dokumentiert.",
    data: {
      name: "CV-Vorsortierung „TalentRank“",
      description:
        "KI-gestütztes System zur Priorisierung eingehender Bewerbungen im Recruiting-Prozess.",
      department: "Personal / HR",
      status: "PILOT",
      purpose: "Eingehende Bewerbungen effizienter vorsortieren und priorisieren.",
      process: "Recruiting / Bewerberauswahl",
      aiType: "CLASSIFICATION",
      provider: "Internal",
      model: "UNKNOWN",
      usageType: "INTERNAL",
      affectedPersons: ["APPLICANTS"],
      decisionType: "PRIORITIZATION",
      dataCategories: ["PERSONAL_DATA", "SPECIAL_CATEGORY_DATA"],
      dataTransferredToExternal: "NO",
      humanReview: "YES",
      approvalProcess: "YES",
      outputControl: "YES",
      logging: "YES",
      interventionAvailable: "YES",
      escalationProcess: "YES",
      directHumanInteraction: "NO",
      aiUsageNotice: "NOT_APPLICABLE",
      aiGeneratedContentPublished: "NO",
      contentHumanReviewed: "NOT_APPLICABLE",
      responsibleRole: "HR Lead",
      trainingProvided: "YES",
      usageRulesDefined: "YES",
      recruitmentScenario: true,
      candidatePrioritisation: true,
      candidateSelection: false,
      qualityChecks: "UNKNOWN",
      biasChecks: "UNKNOWN",
      providerApproval: "UNKNOWN",
      isDemo: true,
      demoKey: "cv-screening",
    },
  },
  "sales-copilot": {
    label: "Interner Vertriebs-Copilot",
    description:
      "Mitarbeiter erstellen Angebote mit externem KI-Anbieter — Schulung, Freigabe und Nutzungsregeln unklar.",
    data: {
      name: "Vertriebs-Copilot „DealAssist“",
      description:
        "Copilot für Vertriebsmitarbeiter zur Erstellung von Angebotsentwürfen und Kundenkommunikation.",
      department: "Vertrieb",
      status: "PILOT",
      purpose: "Angebotsentwürfe und Kundenkommunikation schneller erstellen.",
      process: "Vertriebskommunikation und Angebotserstellung",
      aiType: "GENERATIVE",
      provider: "Microsoft",
      model: "Copilot",
      usageType: "INTERNAL",
      affectedPersons: ["EMPLOYEES", "CUSTOMERS"],
      decisionType: "DECISION_SUPPORT",
      dataCategories: ["PERSONAL_DATA", "CONFIDENTIAL_BUSINESS_DATA"],
      dataTransferredToExternal: "YES",
      humanReview: "UNKNOWN",
      approvalProcess: "UNKNOWN",
      outputControl: "UNKNOWN",
      logging: "UNKNOWN",
      interventionAvailable: "UNKNOWN",
      escalationProcess: "UNKNOWN",
      directHumanInteraction: "NO",
      aiUsageNotice: "NOT_APPLICABLE",
      aiGeneratedContentPublished: "NO",
      contentHumanReviewed: "NOT_APPLICABLE",
      responsibleRole: "",
      trainingProvided: "UNKNOWN",
      usageRulesDefined: "UNKNOWN",
      recruitmentScenario: false,
      candidatePrioritisation: false,
      candidateSelection: false,
      qualityChecks: "UNKNOWN",
      biasChecks: "UNKNOWN",
      providerApproval: "UNKNOWN",
      isDemo: true,
      demoKey: "sales-copilot",
    },
  },
};

export function getDemoCase(key: string) {
  return DEMO_CASES[key] ?? null;
}

export function listDemoCases() {
  return Object.entries(DEMO_CASES).map(([key, value]) => ({
    key,
    label: value.label,
    description: value.description,
  }));
}
